import Mathlib.Analysis.InnerProductSpace.Projection.FiniteDimensional
import Mathlib.Tactic

/-!
# NB-306 projected-dilation isometric core

Associated finding:
`research/nyman_beurling/findings/NB-306-projected-dilation-has-an-exact-linear-scale-isometric-core.md`

Formalized theorem boundary: for the finite canonical sections
`U N = span {g j | 2 ≤ j ≤ N}`, a linear isometry followed by orthogonal projection
onto `U N` preserves every vector in a lower section whose image lies in `U N`. If, for
`q = N / m`, each generator with `2 ≤ j ≤ q` has an image of the form
`a j • g (m*j) + b j • g m`, then `A(U q) ⊆ U N`; under `4 ≤ N`, `2 ≤ m`, and
`2*m ≤ N`, projection is therefore inactive on `A(U q)`, norms are preserved there,
and the projected operator on `U N` has norm exactly one when `g 2 ≠ 0`.

The arbitrary two-term coefficients are a weaker sufficient support hypothesis implied by
the exact NB-290 covariance (whose coefficients are `sqrt m` and `-sqrt m / j`); they are
not an equivalent formalization of that analytic identity. The fractional-part realization
of the dilation and its covariance, nonvanishing of the concrete Nyman generator, the
adjoint identity, singular-value multiplicity/exactness, target/sample statements, and
RH-facing consequences remain outside Lean.
-/

noncomputable section

namespace Mathia.NB306

open Module Submodule

variable (K : Type*) [RCLike K]
variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace K E]

/-! ## Canonical finite sections -/

/-- The canonical section generated by `g 2, ..., g N`. -/
def canonicalSection (g : ℕ → E) (N : ℕ) : Submodule K E :=
  span K (g '' Set.Icc 2 N)

instance canonicalSection_finite (g : ℕ → E) (N : ℕ) :
    FiniteDimensional K (canonicalSection K g N) :=
  FiniteDimensional.span_of_finite K (Set.finite_Icc 2 N |>.image g)

theorem generator_mem_canonicalSection (g : ℕ → E) {j N : ℕ}
    (hj : 2 ≤ j) (hjN : j ≤ N) : g j ∈ canonicalSection K g N :=
  subset_span ⟨j, ⟨hj, hjN⟩, rfl⟩

theorem canonicalSection_mono (g : ℕ → E) {M N : ℕ} (hMN : M ≤ N) :
    canonicalSection K g M ≤ canonicalSection K g N :=
  span_mono (Set.image_mono (Set.Icc_subset_Icc le_rfl hMN))

/-! ## Generic projected isometries -/

/-- Orthogonal projection onto `U` after an isometry, restricted to the domain `U`. -/
def projectedDilation (U : Submodule K E) [U.HasOrthogonalProjection]
    (A : E →ₗᵢ[K] E) : U →L[K] U :=
  U.orthogonalProjectionOnto.comp (A.toContinuousLinearMap.comp U.subtypeL)

@[simp]
theorem projectedDilation_apply (U : Submodule K E) [U.HasOrthogonalProjection]
    (A : E →ₗᵢ[K] E) (v : U) :
    projectedDilation K U A v = U.orthogonalProjectionOnto (A (v : E)) := rfl

theorem projectedDilation_apply_of_mem (U : Submodule K E) [U.HasOrthogonalProjection]
    (A : E →ₗᵢ[K] E) (v : U) (hAv : A (v : E) ∈ U) :
    ((projectedDilation K U A v : U) : E) = A (v : E) := by
  exact U.starProjection_eq_self_iff.mpr hAv

theorem norm_projectedDilation_apply_of_mem (U : Submodule K E) [U.HasOrthogonalProjection]
    (A : E →ₗᵢ[K] E) (v : U) (hAv : A (v : E) ∈ U) :
    ‖projectedDilation K U A v‖ = ‖v‖ := by
  change ‖((projectedDilation K U A v : U) : E)‖ = ‖(v : E)‖
  rw [projectedDilation_apply_of_mem K U A v hAv, A.norm_map]

theorem projectedDilation_norm_le_one (U : Submodule K E) [U.HasOrthogonalProjection]
    (A : E →ₗᵢ[K] E) : ‖projectedDilation K U A‖ ≤ 1 := by
  refine ContinuousLinearMap.opNorm_le_bound _ zero_le_one ?_
  intro v
  rw [one_mul]
  calc
    ‖projectedDilation K U A v‖ ≤ ‖A (v : E)‖ :=
      U.norm_orthogonalProjectionOnto_apply_le _
    _ = ‖v‖ := by simp

theorem projectedDilation_norm_eq_one_of_mem (U : Submodule K E) [U.HasOrthogonalProjection]
    (A : E →ₗᵢ[K] E) (v : U) (hv : v ≠ 0) (hAv : A (v : E) ∈ U) :
    ‖projectedDilation K U A‖ = 1 := by
  apply le_antisymm (projectedDilation_norm_le_one K U A)
  have hratio := (projectedDilation K U A).ratio_le_opNorm v
  rw [norm_projectedDilation_apply_of_mem K U A v hAv,
    div_self (norm_ne_zero_iff.mpr hv)] at hratio
  exact hratio

theorem projectedDilation_core_apply {V U : Submodule K E} [U.HasOrthogonalProjection]
    (A : E →ₗᵢ[K] E) (hVU : V ≤ U) (hA : V.map A.toLinearMap ≤ U)
    {v : E} (hv : v ∈ V) :
    ((projectedDilation K U A ⟨v, hVU hv⟩ : U) : E) = A v := by
  apply projectedDilation_apply_of_mem
  apply hA
  exact ⟨v, hv, rfl⟩

theorem norm_projectedDilation_core {V U : Submodule K E} [U.HasOrthogonalProjection]
    (A : E →ₗᵢ[K] E) (hVU : V ≤ U) (hA : V.map A.toLinearMap ≤ U)
    {v : E} (hv : v ∈ V) :
    ‖projectedDilation K U A ⟨v, hVU hv⟩‖ = ‖v‖ := by
  change ‖((projectedDilation K U A ⟨v, hVU hv⟩ : U) : E)‖ = ‖v‖
  rw [projectedDilation_core_apply K A hVU hA hv]
  exact A.norm_map v

theorem projectedDilation_core_norm_eq_one {V U : Submodule K E} [U.HasOrthogonalProjection]
    (A : E →ₗᵢ[K] E) (hVU : V ≤ U) (hA : V.map A.toLinearMap ≤ U)
    {v : E} (hv : v ∈ V) (hv0 : v ≠ 0) :
    ‖projectedDilation K U A‖ = 1 := by
  apply projectedDilation_norm_eq_one_of_mem K U A ⟨v, hVU hv⟩
  · intro h
    apply hv0
    exact congrArg Subtype.val h
  · apply hA
    exact ⟨v, hv, rfl⟩

/-! ## Finite Nyman index bridge and plateau -/

/-- A local two-generator covariance/support identity maps the lower section into `U N`. -/
theorem dilation_maps_lowerSection (g : ℕ → E) (A : E →ₗᵢ[K] E)
    (N m : ℕ) (_hN : 4 ≤ N) (hm : 2 ≤ m) (_h2m : 2 * m ≤ N)
    (a b : ℕ → K)
    (hcov : ∀ j, 2 ≤ j → j ≤ N / m →
      A (g j) = a j • g (m * j) + b j • g m) :
    (canonicalSection K g (N / m)).map A.toLinearMap ≤ canonicalSection K g N := by
  rw [canonicalSection, LinearMap.map_span_le]
  rintro _ ⟨j, hj, rfl⟩
  have hmpos : 0 < m := by omega
  have hjpos : 0 < j := Nat.zero_lt_two.trans_le hj.1
  have hmN : m ≤ N := by omega
  have hmj : m * j ≤ N := by
    simpa [Nat.mul_comm] using (Nat.le_div_iff_mul_le hmpos).mp hj.2
  change A (g j) ∈ canonicalSection K g N
  rw [hcov j hj.1 hj.2]
  apply add_mem
  · apply smul_mem
    apply generator_mem_canonicalSection K g
    · exact hm.trans (Nat.le_mul_of_pos_right m hjpos)
    · exact hmj
  · exact smul_mem _ _ (generator_mem_canonicalSection K g hm hmN)

theorem lowerSection_le_section (g : ℕ → E) (N m : ℕ) :
    canonicalSection K g (N / m) ≤ canonicalSection K g N :=
  canonicalSection_mono K g (Nat.div_le_self N m)

/-- Projection is inactive on the lower canonical core. -/
theorem nyman_projectedDilation_core_apply (g : ℕ → E) (A : E →ₗᵢ[K] E)
    (N m : ℕ) (hN : 4 ≤ N) (hm : 2 ≤ m) (h2m : 2 * m ≤ N)
    (a b : ℕ → K)
    (hcov : ∀ j, 2 ≤ j → j ≤ N / m →
      A (g j) = a j • g (m * j) + b j • g m)
    {v : E} (hv : v ∈ canonicalSection K g (N / m)) :
    ((projectedDilation K (canonicalSection K g N) A
      ⟨v, lowerSection_le_section K g N m hv⟩ : canonicalSection K g N) : E) = A v := by
  exact projectedDilation_core_apply K A (lowerSection_le_section K g N m)
    (dilation_maps_lowerSection K g A N m hN hm h2m a b hcov) hv

/-- Every vector in `U (N/m)` is norm-preserved by projected dilation. -/
theorem norm_nyman_projectedDilation_core (g : ℕ → E) (A : E →ₗᵢ[K] E)
    (N m : ℕ) (hN : 4 ≤ N) (hm : 2 ≤ m) (h2m : 2 * m ≤ N)
    (a b : ℕ → K)
    (hcov : ∀ j, 2 ≤ j → j ≤ N / m →
      A (g j) = a j • g (m * j) + b j • g m)
    {v : E} (hv : v ∈ canonicalSection K g (N / m)) :
    ‖projectedDilation K (canonicalSection K g N) A
      ⟨v, lowerSection_le_section K g N m hv⟩‖ = ‖v‖ := by
  exact norm_projectedDilation_core K A (lowerSection_le_section K g N m)
    (dilation_maps_lowerSection K g A N m hN hm h2m a b hcov) hv

/-- Under `2*m ≤ N`, the projected finite-section dilation has operator norm one. -/
theorem norm_nyman_projectedDilation (g : ℕ → E) (A : E →ₗᵢ[K] E)
    (N m : ℕ) (hN : 4 ≤ N) (hm : 2 ≤ m) (h2m : 2 * m ≤ N)
    (hg2 : g 2 ≠ 0) (a b : ℕ → K)
    (hcov : ∀ j, 2 ≤ j → j ≤ N / m →
      A (g j) = a j • g (m * j) + b j • g m) :
    ‖projectedDilation K (canonicalSection K g N) A‖ = 1 := by
  have hmpos : 0 < m := by omega
  have hq : 2 ≤ N / m := (Nat.le_div_iff_mul_le hmpos).mpr h2m
  apply projectedDilation_core_norm_eq_one K A (lowerSection_le_section K g N m)
    (dilation_maps_lowerSection K g A N m hN hm h2m a b hcov)
    (generator_mem_canonicalSection K g le_rfl hq) hg2

#print axioms dilation_maps_lowerSection
#print axioms nyman_projectedDilation_core_apply
#print axioms norm_nyman_projectedDilation_core
#print axioms norm_nyman_projectedDilation

end Mathia.NB306
